version: "3"
# see: https://taskfile.dev/usage/

tasks:
  fmt:
    shopt:
      - globstar
    cmds:
      - stylua lua/**/*.lua
  check-fmt:
    shopt:
      - globstar
    cmds:
      - stylua --check lua/**/*.lua
