name: Checks for push

on: push

jobs:
  path-filter:
    outputs:
      actions: ${{steps.changes.outputs.actions}}
      lua: ${{steps.changes.outputs.lua}}
    runs-on: ubuntu-latest
    permissions: {}
    steps:
      - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6
      - uses: dorny/paths-filter@de90cc6fb38fc0963ad72b210f1f284cd68cea36 # v3.0.2
        id: changes
        with:
          filters: |
            actions:
              - .github/workflows/*.yml
              - .github/workflows/*.yaml
              - aqua.yaml
            lua:
              - .github/workflows/push.yml
              - .github/workflows/_check-lua.yml
              - ./**/*.lua
              - taskfile.yml
              - .luacheckrc
  check-actions:
    needs: path-filter
    if: needs.path-filter.outputs.actions == 'true'
    uses: ./.github/workflows/_check-actions.yml
    permissions:
      contents: read
  check-lua:
    needs: path-filter
    if: needs.path-filter.outputs.lua == 'true'
    uses: ./.github/workflows/_check-lua.yml
    permissions:
      contents: read
